basePath: /api/magic-circle
definitions:
  direction.Direction:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  direction.GetDirectionsResp:
    properties:
      directions:
        items:
          $ref: '#/definitions/direction.Direction'
        type: array
    type: object
  institute.GetInstitutesResp:
    properties:
      institutes:
        items:
          $ref: '#/definitions/institute.Institute'
        type: array
    type: object
  institute.Institute:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  profile.GetAllProfilesResp:
    properties:
      profiles:
        items:
          $ref: '#/definitions/profile.Profile'
        type: array
    type: object
  profile.Profile:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  sector.CreateSectorReq:
    properties:
      coords:
        type: string
    type: object
  sector.Sector:
    properties:
      coords:
        type: string
      int:
        type: integer
    type: object
info:
  contact: {}
  description: This is a server to get projects from github
  title: Magic-Circle API
  version: "1.0"
paths:
  /v1/direction:
    get:
      description: return all directions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/direction.GetDirectionsResp'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all directions
  /v1/institute:
    get:
      description: return all institutes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/institute.GetInstitutesResp'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all institutes
  /v1/profiles:
    get:
      description: return all profiles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/profile.GetAllProfilesResp'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all profiles
  /v1/sector:
    post:
      consumes:
      - application/json
      description: |-
        create sector according to giving coords
        coords is unique string
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/sector.CreateSectorReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/sector.Sector'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create Sector
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
