// Code generated by entc, DO NOT EDIT.

package profile

const (
	// Label holds the string label denoting the profile type in the database.
	Label = "profile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeVariants holds the string denoting the variants edge name in mutations.
	EdgeVariants = "Variants"
	// Table holds the table name of the profile in the database.
	Table = "Profile"
	// VariantsTable is the table that holds the Variants relation/edge.
	VariantsTable = "Variant"
	// VariantsInverseTable is the table name for the Variant entity.
	// It exists in this package in order to avoid circular dependency with the "variant" package.
	VariantsInverseTable = "Variant"
	// VariantsColumn is the table column denoting the Variants relation/edge.
	VariantsColumn = "profile_id"
)

// Columns holds all SQL columns for profile fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
