// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/0B1t322/Magic-Circle/ent/admin"
	"github.com/0B1t322/Magic-Circle/ent/institute"
)

// Admin is the model entity for the Admin schema.
type Admin struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Login holds the value of the "login" field.
	Login string `json:"login,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"password,omitempty"`
	// InstituteID holds the value of the "institute_id" field.
	InstituteID int `json:"institute_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AdminQuery when eager-loading is set.
	Edges AdminEdges `json:"edges"`
}

// AdminEdges holds the relations/edges for other nodes in the graph.
type AdminEdges struct {
	// Institute holds the value of the Institute edge.
	Institute *Institute `json:"Institute,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// InstituteOrErr returns the Institute value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdminEdges) InstituteOrErr() (*Institute, error) {
	if e.loadedTypes[0] {
		if e.Institute == nil {
			// The edge Institute was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: institute.Label}
		}
		return e.Institute, nil
	}
	return nil, &NotLoadedError{edge: "Institute"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Admin) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case admin.FieldID, admin.FieldInstituteID:
			values[i] = new(sql.NullInt64)
		case admin.FieldLogin, admin.FieldPassword:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Admin", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Admin fields.
func (a *Admin) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case admin.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		case admin.FieldLogin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field login", values[i])
			} else if value.Valid {
				a.Login = value.String
			}
		case admin.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				a.Password = value.String
			}
		case admin.FieldInstituteID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field institute_id", values[i])
			} else if value.Valid {
				a.InstituteID = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryInstitute queries the "Institute" edge of the Admin entity.
func (a *Admin) QueryInstitute() *InstituteQuery {
	return (&AdminClient{config: a.config}).QueryInstitute(a)
}

// Update returns a builder for updating this Admin.
// Note that you need to call Admin.Unwrap() before calling this method if this Admin
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Admin) Update() *AdminUpdateOne {
	return (&AdminClient{config: a.config}).UpdateOne(a)
}

// Unwrap unwraps the Admin entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Admin) Unwrap() *Admin {
	tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Admin is not a transactional entity")
	}
	a.config.driver = tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Admin) String() string {
	var builder strings.Builder
	builder.WriteString("Admin(")
	builder.WriteString(fmt.Sprintf("id=%v", a.ID))
	builder.WriteString(", login=")
	builder.WriteString(a.Login)
	builder.WriteString(", password=")
	builder.WriteString(a.Password)
	builder.WriteString(", institute_id=")
	builder.WriteString(fmt.Sprintf("%v", a.InstituteID))
	builder.WriteByte(')')
	return builder.String()
}

// Admins is a parsable slice of Admin.
type Admins []*Admin

func (a Admins) config(cfg config) {
	for _i := range a {
		a[_i].config = cfg
	}
}
