// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/0B1t322/Magic-Circle/ent/direction"
	"github.com/0B1t322/Magic-Circle/ent/institute"
	"github.com/0B1t322/Magic-Circle/ent/predicate"
	"github.com/0B1t322/Magic-Circle/ent/profile"
)

// DirectionUpdate is the builder for updating Direction entities.
type DirectionUpdate struct {
	config
	hooks    []Hook
	mutation *DirectionMutation
}

// Where appends a list predicates to the DirectionUpdate builder.
func (du *DirectionUpdate) Where(ps ...predicate.Direction) *DirectionUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetName sets the "name" field.
func (du *DirectionUpdate) SetName(s string) *DirectionUpdate {
	du.mutation.SetName(s)
	return du
}

// SetInstituteID sets the "institute_id" field.
func (du *DirectionUpdate) SetInstituteID(i int) *DirectionUpdate {
	du.mutation.SetInstituteID(i)
	return du
}

// SetInstitute sets the "Institute" edge to the Institute entity.
func (du *DirectionUpdate) SetInstitute(i *Institute) *DirectionUpdate {
	return du.SetInstituteID(i.ID)
}

// AddProfileIDs adds the "Profile" edge to the Profile entity by IDs.
func (du *DirectionUpdate) AddProfileIDs(ids ...int) *DirectionUpdate {
	du.mutation.AddProfileIDs(ids...)
	return du
}

// AddProfile adds the "Profile" edges to the Profile entity.
func (du *DirectionUpdate) AddProfile(p ...*Profile) *DirectionUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return du.AddProfileIDs(ids...)
}

// Mutation returns the DirectionMutation object of the builder.
func (du *DirectionUpdate) Mutation() *DirectionMutation {
	return du.mutation
}

// ClearInstitute clears the "Institute" edge to the Institute entity.
func (du *DirectionUpdate) ClearInstitute() *DirectionUpdate {
	du.mutation.ClearInstitute()
	return du
}

// ClearProfile clears all "Profile" edges to the Profile entity.
func (du *DirectionUpdate) ClearProfile() *DirectionUpdate {
	du.mutation.ClearProfile()
	return du
}

// RemoveProfileIDs removes the "Profile" edge to Profile entities by IDs.
func (du *DirectionUpdate) RemoveProfileIDs(ids ...int) *DirectionUpdate {
	du.mutation.RemoveProfileIDs(ids...)
	return du
}

// RemoveProfile removes "Profile" edges to Profile entities.
func (du *DirectionUpdate) RemoveProfile(p ...*Profile) *DirectionUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return du.RemoveProfileIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DirectionUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(du.hooks) == 0 {
		if err = du.check(); err != nil {
			return 0, err
		}
		affected, err = du.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DirectionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = du.check(); err != nil {
				return 0, err
			}
			du.mutation = mutation
			affected, err = du.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(du.hooks) - 1; i >= 0; i-- {
			if du.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = du.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, du.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (du *DirectionUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DirectionUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DirectionUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (du *DirectionUpdate) check() error {
	if _, ok := du.mutation.InstituteID(); du.mutation.InstituteCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"Institute\"")
	}
	return nil
}

func (du *DirectionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   direction.Table,
			Columns: direction.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: direction.FieldID,
			},
		},
	}
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: direction.FieldName,
		})
	}
	if du.mutation.InstituteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   direction.InstituteTable,
			Columns: []string{direction.InstituteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: institute.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.InstituteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   direction.InstituteTable,
			Columns: []string{direction.InstituteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: institute.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if du.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   direction.ProfileTable,
			Columns: []string{direction.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: profile.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.RemovedProfileIDs(); len(nodes) > 0 && !du.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   direction.ProfileTable,
			Columns: []string{direction.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: profile.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   direction.ProfileTable,
			Columns: []string{direction.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: profile.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{direction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// DirectionUpdateOne is the builder for updating a single Direction entity.
type DirectionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DirectionMutation
}

// SetName sets the "name" field.
func (duo *DirectionUpdateOne) SetName(s string) *DirectionUpdateOne {
	duo.mutation.SetName(s)
	return duo
}

// SetInstituteID sets the "institute_id" field.
func (duo *DirectionUpdateOne) SetInstituteID(i int) *DirectionUpdateOne {
	duo.mutation.SetInstituteID(i)
	return duo
}

// SetInstitute sets the "Institute" edge to the Institute entity.
func (duo *DirectionUpdateOne) SetInstitute(i *Institute) *DirectionUpdateOne {
	return duo.SetInstituteID(i.ID)
}

// AddProfileIDs adds the "Profile" edge to the Profile entity by IDs.
func (duo *DirectionUpdateOne) AddProfileIDs(ids ...int) *DirectionUpdateOne {
	duo.mutation.AddProfileIDs(ids...)
	return duo
}

// AddProfile adds the "Profile" edges to the Profile entity.
func (duo *DirectionUpdateOne) AddProfile(p ...*Profile) *DirectionUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return duo.AddProfileIDs(ids...)
}

// Mutation returns the DirectionMutation object of the builder.
func (duo *DirectionUpdateOne) Mutation() *DirectionMutation {
	return duo.mutation
}

// ClearInstitute clears the "Institute" edge to the Institute entity.
func (duo *DirectionUpdateOne) ClearInstitute() *DirectionUpdateOne {
	duo.mutation.ClearInstitute()
	return duo
}

// ClearProfile clears all "Profile" edges to the Profile entity.
func (duo *DirectionUpdateOne) ClearProfile() *DirectionUpdateOne {
	duo.mutation.ClearProfile()
	return duo
}

// RemoveProfileIDs removes the "Profile" edge to Profile entities by IDs.
func (duo *DirectionUpdateOne) RemoveProfileIDs(ids ...int) *DirectionUpdateOne {
	duo.mutation.RemoveProfileIDs(ids...)
	return duo
}

// RemoveProfile removes "Profile" edges to Profile entities.
func (duo *DirectionUpdateOne) RemoveProfile(p ...*Profile) *DirectionUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return duo.RemoveProfileIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DirectionUpdateOne) Select(field string, fields ...string) *DirectionUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Direction entity.
func (duo *DirectionUpdateOne) Save(ctx context.Context) (*Direction, error) {
	var (
		err  error
		node *Direction
	)
	if len(duo.hooks) == 0 {
		if err = duo.check(); err != nil {
			return nil, err
		}
		node, err = duo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DirectionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = duo.check(); err != nil {
				return nil, err
			}
			duo.mutation = mutation
			node, err = duo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(duo.hooks) - 1; i >= 0; i-- {
			if duo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = duo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, duo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DirectionUpdateOne) SaveX(ctx context.Context) *Direction {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DirectionUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DirectionUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (duo *DirectionUpdateOne) check() error {
	if _, ok := duo.mutation.InstituteID(); duo.mutation.InstituteCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"Institute\"")
	}
	return nil
}

func (duo *DirectionUpdateOne) sqlSave(ctx context.Context) (_node *Direction, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   direction.Table,
			Columns: direction.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: direction.FieldID,
			},
		},
	}
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Direction.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, direction.FieldID)
		for _, f := range fields {
			if !direction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != direction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: direction.FieldName,
		})
	}
	if duo.mutation.InstituteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   direction.InstituteTable,
			Columns: []string{direction.InstituteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: institute.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.InstituteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   direction.InstituteTable,
			Columns: []string{direction.InstituteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: institute.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if duo.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   direction.ProfileTable,
			Columns: []string{direction.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: profile.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.RemovedProfileIDs(); len(nodes) > 0 && !duo.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   direction.ProfileTable,
			Columns: []string{direction.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: profile.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   direction.ProfileTable,
			Columns: []string{direction.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: profile.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Direction{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{direction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
