// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/0B1t322/Magic-Circle/ent/direction"
	"github.com/0B1t322/Magic-Circle/ent/institute"
	"github.com/0B1t322/Magic-Circle/ent/profile"
	"github.com/0B1t322/Magic-Circle/ent/variant"
)

// Variant is the model entity for the Variant schema.
type Variant struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DirectionID holds the value of the "direction_id" field.
	DirectionID int `json:"direction_id,omitempty"`
	// ProfileID holds the value of the "profile_id" field.
	ProfileID int `json:"profile_id,omitempty"`
	// InsituteID holds the value of the "insitute_id" field.
	InsituteID int `json:"insitute_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VariantQuery when eager-loading is set.
	Edges VariantEdges `json:"edges"`
}

// VariantEdges holds the relations/edges for other nodes in the graph.
type VariantEdges struct {
	// Insitute holds the value of the Insitute edge.
	Insitute *Institute `json:"Insitute,omitempty"`
	// Direction holds the value of the Direction edge.
	Direction *Direction `json:"Direction,omitempty"`
	// Profile holds the value of the Profile edge.
	Profile *Profile `json:"Profile,omitempty"`
	// AdjacentTables holds the value of the AdjacentTables edge.
	AdjacentTables []*AdjacentTable `json:"AdjacentTables,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// InsituteOrErr returns the Insitute value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VariantEdges) InsituteOrErr() (*Institute, error) {
	if e.loadedTypes[0] {
		if e.Insitute == nil {
			// The edge Insitute was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: institute.Label}
		}
		return e.Insitute, nil
	}
	return nil, &NotLoadedError{edge: "Insitute"}
}

// DirectionOrErr returns the Direction value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VariantEdges) DirectionOrErr() (*Direction, error) {
	if e.loadedTypes[1] {
		if e.Direction == nil {
			// The edge Direction was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: direction.Label}
		}
		return e.Direction, nil
	}
	return nil, &NotLoadedError{edge: "Direction"}
}

// ProfileOrErr returns the Profile value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VariantEdges) ProfileOrErr() (*Profile, error) {
	if e.loadedTypes[2] {
		if e.Profile == nil {
			// The edge Profile was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: profile.Label}
		}
		return e.Profile, nil
	}
	return nil, &NotLoadedError{edge: "Profile"}
}

// AdjacentTablesOrErr returns the AdjacentTables value or an error if the edge
// was not loaded in eager-loading.
func (e VariantEdges) AdjacentTablesOrErr() ([]*AdjacentTable, error) {
	if e.loadedTypes[3] {
		return e.AdjacentTables, nil
	}
	return nil, &NotLoadedError{edge: "AdjacentTables"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Variant) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case variant.FieldID, variant.FieldDirectionID, variant.FieldProfileID, variant.FieldInsituteID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Variant", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Variant fields.
func (v *Variant) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case variant.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			v.ID = int(value.Int64)
		case variant.FieldDirectionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field direction_id", values[i])
			} else if value.Valid {
				v.DirectionID = int(value.Int64)
			}
		case variant.FieldProfileID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field profile_id", values[i])
			} else if value.Valid {
				v.ProfileID = int(value.Int64)
			}
		case variant.FieldInsituteID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field insitute_id", values[i])
			} else if value.Valid {
				v.InsituteID = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryInsitute queries the "Insitute" edge of the Variant entity.
func (v *Variant) QueryInsitute() *InstituteQuery {
	return (&VariantClient{config: v.config}).QueryInsitute(v)
}

// QueryDirection queries the "Direction" edge of the Variant entity.
func (v *Variant) QueryDirection() *DirectionQuery {
	return (&VariantClient{config: v.config}).QueryDirection(v)
}

// QueryProfile queries the "Profile" edge of the Variant entity.
func (v *Variant) QueryProfile() *ProfileQuery {
	return (&VariantClient{config: v.config}).QueryProfile(v)
}

// QueryAdjacentTables queries the "AdjacentTables" edge of the Variant entity.
func (v *Variant) QueryAdjacentTables() *AdjacentTableQuery {
	return (&VariantClient{config: v.config}).QueryAdjacentTables(v)
}

// Update returns a builder for updating this Variant.
// Note that you need to call Variant.Unwrap() before calling this method if this Variant
// was returned from a transaction, and the transaction was committed or rolled back.
func (v *Variant) Update() *VariantUpdateOne {
	return (&VariantClient{config: v.config}).UpdateOne(v)
}

// Unwrap unwraps the Variant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (v *Variant) Unwrap() *Variant {
	tx, ok := v.config.driver.(*txDriver)
	if !ok {
		panic("ent: Variant is not a transactional entity")
	}
	v.config.driver = tx.drv
	return v
}

// String implements the fmt.Stringer.
func (v *Variant) String() string {
	var builder strings.Builder
	builder.WriteString("Variant(")
	builder.WriteString(fmt.Sprintf("id=%v", v.ID))
	builder.WriteString(", direction_id=")
	builder.WriteString(fmt.Sprintf("%v", v.DirectionID))
	builder.WriteString(", profile_id=")
	builder.WriteString(fmt.Sprintf("%v", v.ProfileID))
	builder.WriteString(", insitute_id=")
	builder.WriteString(fmt.Sprintf("%v", v.InsituteID))
	builder.WriteByte(')')
	return builder.String()
}

// Variants is a parsable slice of Variant.
type Variants []*Variant

func (v Variants) config(cfg config) {
	for _i := range v {
		v[_i].config = cfg
	}
}
