// Code generated by entc, DO NOT EDIT.

package institute

const (
	// Label holds the string label denoting the institute type in the database.
	Label = "institute"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeDirections holds the string denoting the directions edge name in mutations.
	EdgeDirections = "Directions"
	// EdgeAdmins holds the string denoting the admins edge name in mutations.
	EdgeAdmins = "Admins"
	// Table holds the table name of the institute in the database.
	Table = "Institute"
	// DirectionsTable is the table that holds the Directions relation/edge.
	DirectionsTable = "Direction"
	// DirectionsInverseTable is the table name for the Direction entity.
	// It exists in this package in order to avoid circular dependency with the "direction" package.
	DirectionsInverseTable = "Direction"
	// DirectionsColumn is the table column denoting the Directions relation/edge.
	DirectionsColumn = "institute_id"
	// AdminsTable is the table that holds the Admins relation/edge.
	AdminsTable = "Admin"
	// AdminsInverseTable is the table name for the Admin entity.
	// It exists in this package in order to avoid circular dependency with the "admin" package.
	AdminsInverseTable = "Admin"
	// AdminsColumn is the table column denoting the Admins relation/edge.
	AdminsColumn = "institute_id"
)

// Columns holds all SQL columns for institute fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
